### ISSUE TITLE
On signup, handleSignUp.php doesn't redirect anywhere, just has a blank screen.

### ISSUE THREAD

**Issue by Aerospace35** [aminyasser/twitter-clone#1]
I found some inconsistencies with the spelling of "Validator" and "validation" and also in Validator.php "Requireimage.php" was different than the actual filename

**Comment by Aerospace35** [comment]
![2021-05-11-082018_1440x900_scrot](https://user-images.githubusercontent.com/76886939/117831479-d7499f00-b231-11eb-9125-a1e025fefac4.png)

**Comment by aminyasser** [comment]
Hey there!
Thank you for opening this issue, the problem was in my xampp localhost environment is not case sensitive with file names.
I change it right now you can try again and tell me if everything works fine. 
Also, i change the validation file spelling mistake.

**Comment by Aerospace35** [comment]
That was quick! Thanks for the update. Unfortunately, based on my diagnostics and testing, the handleSignUp.php still fails, leading to the white screen. I probably have an issue with my configuration or my mySQL settings, somewhere. If you have any other ideas I'd be happy to try them!

Have a nice day.

**Comment by aminyasser** [comment]
I am using XAMPP environment and unfortunately and not familiar with other environments.
Can you try adding "php_value display_errors 1" to the .httaccses file,  i think it will show the specific error happen with you but i am not sure.

**Comment by Aerospace35** [comment]
The error finding worked! Does this help in any way?

`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'following' doesn't have a default value in /var/www/html/Social/Chitter2/core/classes/User.php:66 Stack trace: #0 /var/www/html/Social/Chitter2/core/classes/User.php(66): PDOStatement->execute() #1 /var/www/html/Social/Chitter2/handle/handleSignUp.php(43): User::register('brodiefriesen77...', '653c6617e0399aa...', 'Brodie Friesen', 'brodiefriesen') #2 {main} thrown in /var/www/html/Social/Chitter2/core/classes/User.php on line 66`

**Comment by aminyasser** [comment]
Yes, it helps.
The problem was i add following/followers fields when development and don't use it. my XMAPP environment assume the default value of this fields is 0. 
I think other environments must make default values. 
I commit a new SQL file to solve this error. 
If you don't want to delete DB and import new  
Just type this in your SQL 

ALTER TABLE `users`
  DROP `following`,
  DROP `followers`; 

I hope this solve the problem.

**Comment by Aerospace35** [comment]
It solved that one, but revealed another…
`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1364 Field 'bio' doesn't have a default value in /var/www/html/Social/Chitter2/core/classes/User.php:66 Stack trace: #0 /var/www/html/Social/Chitter2/core/classes/User.php(66): PDOStatement->execute() #1 /var/www/html/Social/Chitter2/handle/handleSignUp.php(43): User::register('brodiefriesen77...', '36366b49b73cc1e...', 'Brodie Friesen', 'Brodiefriesen') #2 {main} thrown in /var/www/html/Social/Chitter2/core/classes/User.php on line 66 `

I will poke around and see if there is a solution online rather than bother you!

**Comment by aminyasser** [comment]
Don't worry. you aren't bother me. 
Sorry for late i just saw the comment now.
It's the same default type problem but in another way, thank you for notifying me.
I will commit changes in SQL file. and you can type this in your SQL.

```sql
ALTER TABLE `users` 
CHANGE `bio` `bio` VARCHAR(140) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL DEFAULT '', 
CHANGE `location` `location` VARCHAR(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL DEFAULT '',
CHANGE `website` `website` VARCHAR(255) CHARACTER SET utf16 COLLATE utf16_unicode_ci NOT NULL DEFAULT ''; 
``` 
I hope everything work fine.

**Comment by aminyasser** [comment]
I commit a new change in ajax files also check it before trying.
because it will make ajax buttons don't work in other environments. it was just a file path error. 
so, pull the recent changes or download the project again and try. 
i think it will work fine.

**Comment by Aerospace35** [comment]
It worked!! Thank you so much, this is awesome. Have a great day, and thanks again! :)
