### ISSUE TITLE
How to add comment input box without a modal

### ISSUE THREAD

**Issue by ryanjacl** [aminyasser/twitter-clone#11]
Can you reply how to add just "write a comment" input box below the post not a comment button

**Comment by australopythecu** [comment]
Sample code

<div class="retweet-popup-body-wrap">
		<div class="retweet-popup-heading">
			<span><i class="close-retweet-popup fa fa-4x fa-times" aria-hidden="true"></i></span>
			<h2>Comment this Tweet</h2>
            <small>Your behavior and comments count. We don´t allow bullying, harassment, nor sexual content/conduct.</small>
		</div>
		<div class="retweet-popup-input">
			<div class="retweet-popup-input-inner">
				
			<center>
                 <input  class="retweet-msg" type="text" placeholder="Add your Comment"/>
                  	<button class="btn btn-primary comment-it" 
				data-tweet="<?php echo $tweet_id;?>"
				data-user="<?php echo $user_id;?>"
				data-tmp="<?php echo $retweet_comment; ?>" 
				data-qoq="<?php echo $qoq; ?>" 
			 type="submit"><i class="fas fa-pencil-alt" aria-hidden="true"></i> Add Comment</button>
			</center>
			</div>
		</div>

The comment form validate via ajax through the class "comment-it", so you need the js files always.
